<?php

namespace Patrycja\WypozyczBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AActorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AActorsRepository extends EntityRepository
{
}
